### PR TITLE
Minor rework of system.

### PR DESCRIPTION
**Pull request by CoolSlimbo**
I was not going to touch the video creation part yet. But enjoy these performance changes.

### CODE REVIEW

**Review by CodifiedDev — CHANGES_REQUESTED** [review]
Most provided changes are beneficial and meet pushing guidelines, except for commit 2c9083c37edb9d2338e65a3435c3794d489e0eb2. Currently the for loop begins at 1 to avoid the common ‘lounge’ pinned at the top of many ‘subreddits’. To supersede this functionality a method for confirming the actual content of the scraped data must be created.

**Comment by CoolSlimbo** [comment]
Could I please have a link to the pushing guidelines? As I do not seem to be able to find any?

**Comment by CodifiedDev** [comment]
> Could I please have a link to the pushing guidelines? As I do not seem to be able to find any?

Contribution guidelines can be found [here].(https://github.com/CodifiedDev/ARSA/blob/master/CONTRIBUTING.md)

**Comment by CoolSlimbo** [comment]
I do believe the changes are up to standard, having reverted one of the changes?

**Pull request merged**
